inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    
Metrics/MethodLength:
    Exclude:
      - spec/**/
