#!/bin/bash

set -e

curl_me() {
  (set -x; curl -v \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3" \
    -H "Content-Type: application/json" \
    -H "User-Agent: Octokit Ruby Gem 4.2.0" \
    https://api.github.com${1} > \
  spec/webmock/api_get_${2}.json.gz)
}

curl_me "/repos/jekyll/github-metadata?per_page=100" "repo"
curl_me "/repos/jekyll/github-metadata/contributors", "repo_contributors"
curl_me "/repos/jekyll/github-metadata/releases", "repo_releases"
curl_me "/orgs/jekyll", "org"
curl_me "/orgs/jekyll/public_members", "org_members"
curl_me "/users/jekyll/repos?per_page=100&type=public", "owner_repos"
